### ISSUE TITLE
Implementation Task - Create gigya change email aspx page (TFS 39054)

### ISSUE THREAD

**Issue by mkoza178** [mkoza178/PJACS-Implemenation#19]

**Comment by beckywallace** [comment]
When logging in with an email that is registered to multiple accounts, selecting one account, and then changing the email, email is being changed for ALL registrations, not just the selected account.  

Current registrations are under bwallace@advancelocal.com / mg2test

**Comment by mkoza178** [comment]
Not following you. 

Keep in mind, if you update an email, it will also be updated for the other accounts it's attached to. This is expected because it's 1 email attached to multiple accounts. Not multiple emails attached to multiple accounts.
