### ISSUE TITLE
Member home button on registration confirmation directs subscriber to member site without site code (TFS 39064)

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/PJACS-Implemenation#24]
When registering an account, the "Member Home" link is directing the subscriber to https://test-member.nj.com/index.aspx.  This should direct to the member page that includes the site code.

**Comment by beckywallace** [comment]
did the workflow change here?  I no longer have a button for member home, instead have a "sign in" button that presents the Gigya modal:

![image](https://user-images.githubusercontent.com/25667903/40379692-6e6e3148-5dbc-11e8-9961-8fd53ab1ba3c.png)

After signing in, the modal disappears, and the page still has the same options:
![image](https://user-images.githubusercontent.com/25667903/40379742-91c55eaa-5dbc-11e8-93c9-003c636e7237.png)

**Comment by mkoza178** [comment]
I did not change, this currently exists in Prod for all sites.

When matching or subscribing, if the email already exists we do not log you in automatically. We force you to log in. 
If the email does not exist, we log you in immediately.

**Comment by beckywallace** [comment]
In prod, I'm presented with a button to go to member home after registering, not a sign-in button.  Once I'm at member home, I then have the option to Log In.  

![image](https://user-images.githubusercontent.com/25667903/40388607-9f643798-5dd5-11e8-928c-bd93fc1134a8.png)

**Comment by mkoza178** [comment]
Well that's odd. You work completely different than all clients. I expect a 'Log In' button in that scenario because, especially in the future, it may not always go to the subcon site.
