### ISSUE TITLE
CREDIT CARD UPDATE 

### ISSUE THREAD

**Issue by jvanzomeren** [mkoza178/PJACS-Implemenation#27]
I entered a credit card update for sub id 0010594018 card type was updated as 07 should be VI

**Comment by mkoza178** [comment]
Parth has reviewed. We are passing VI:
https://prnt.sc/jib7j1
https://prnt.sc/jib8ff

We will need some assistance on debugging this.

**Comment by mkoza178** [comment]
We found the source of the error:
https://prnt.sc/jico6w

Seems the use case is when an Edgil authorization is pending on the Account in CJ and it blocks us from updating. Determining how to solve for this case.

**Comment by mkoza178** [comment]
@jvanzomeren Any update on if we are going to keep change payment for go live? I know Jack was looking into that issue in CJ.

**Comment by mkoza178** [comment]
Will not be visible for go live.
