### ISSUE TITLE
Multiple Payments (TFS 39083)

### ISSUE THREAD

**Issue by jvanzomeren** [mkoza178/PJACS-Implemenation#29]
From the Payment Confirmation page you can hit the browser back button and return the payment page.  When you hit submit it creates a 2nd payment on the account.   We should limit the number of payments per subscription to one in 24hours 
<img width="1153" alt="screen shot 2018-05-15 at 3 39 41 pm" src="https://user-images.githubusercontent.com/25616598/40082602-0fd0c35e-5857-11e8-8926-3980f2484280.png">

**Comment by beckywallace** [comment]
Attempting with PBM account 0014058671  Initial payment successful, hitting back button - receive the following error:

![image](https://user-images.githubusercontent.com/25667903/40389499-42f680f8-5dd8-11e8-9028-f82a11c57fa1.png)
