### ISSUE TITLE
Payment with Tip (TFS 39085)

### ISSUE THREAD

**Issue by jvanzomeren** [mkoza178/PJACS-Implemenation#31]
We created a payment with tip.  Both the Payment Amount and the tip amount were shown in the in the payment amount.   Tip needs to show differently.   Print Screens of the correct entry are incoming.

**Comment by jvanzomeren** [comment]
[Tips One Time .docx](https://github.com/mkoza178/PJACS-Implemenation/files/2006983/Tips.One.Time.docx)
[Recurring Tips EZ Pay.docx](https://github.com/mkoza178/PJACS-Implemenation/files/2006984/Recurring.Tips.EZ.Pay.docx)

**Comment by mkoza178** [comment]
This is ready. Please test and confirm in NJ and AL. 
You will see two new event types:
New Event 997-TipMemo (one time payments)
New Event 996-RECURRINGTIP  (ezpay signup)
