### ISSUE TITLE
3rd complaint attempt not giving correct error (TFS 39090)

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/PJACS-Implemenation#33]
When subscriber attempts a 3rd complaint for same day, they should get an error to call customer service.  When within an hour of the second complaint, they are receiving the error that they have submitted a complaint in the last hour.

**Comment by mkoza178** [comment]
Becky what login can I use to test this? And what date should I select in the calendar?

**Comment by mkoza178** [comment]
TFS includes this logic:
1. An end user can make as many complaints as they want for a day.
2. We only allow 2 complaints for an effective date.
3. If Credit or Redelivery Next Day is chosen for an effective date then they do not get to submit anymore complaints for that effective date.

**Comment by beckywallace** [comment]
The first event below was submitted for today's date, within the redelivery window, and the second complaint for yesterday, also within the redelivery window.  Attempting to submit a second complaint for today resulted in error message.  Should have allowed second complaint for today:

![image](https://user-images.githubusercontent.com/25667903/40980096-47f7a80a-689d-11e8-88b5-d517655e72bd.png)

![image](https://user-images.githubusercontent.com/25667903/40980194-7411e4a0-689d-11e8-8775-3a20bd80d4ab.png)

**Comment by mkoza178** [comment]
Ready to re-test.
