### ISSUE TITLE
AL - unable to log in to member site

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/PJACS-Implemenation#34]
When attempting to log in to the AL member site, either with an existing login or a new registration username / password, user is presented with the following screen:

![image](https://user-images.githubusercontent.com/25667903/40244961-e3b2cecc-5a89-11e8-84dc-3ee372bdd043.png)

The admin does not contain any information to indicate what the error is.

bwallace@advancelocal.com / mg2test
bwallace@advancecentralservices.com / mg2test

**Comment by mkoza178** [comment]
This will be solved by the AL migration to Gigya.
