### ISSUE TITLE
New Start Change Emails failing (TFS 39111)

### ISSUE THREAD

**Issue by mkoza178** [mkoza178/PJACS-Implemenation#36]
When doing new starts, the ChangeEmail event (21) was failing. You can re-test by doing new starts.

**Comment by beckywallace** [comment]
change email event is successful (event ID 1368913), but email address is not showing in CJ:

![image](https://user-images.githubusercontent.com/25667903/40366192-297d4fa8-5d9c-11e8-99c9-89ff5e5a270b.png)

**Comment by mkoza178** [comment]
Confirmed, re-opened with Parth.

**Comment by mkoza178** [comment]
Becky can you retry, we reviewed further and see the email being updated:
http://prntscr.com/jlcciv
If the record was not updated you would see an error like below
http://prntscr.com/jlcd3i

**Comment by mkoza178** [comment]
Spoke on the call, model change is necessary for AL and NJ.

**Comment by mkoza178** [comment]
After reviewing the suggested change, the logic is becoming very complex. Parth and I agree we need to scale this back or it could be unmanageable. 

The options we presented:
1. We input emails at the household level, like we did for AL
2. We don't input email at all

Awaiting Jon's feedback.

**Comment by mkoza178** [comment]
Per Jon:

Do not send the email to CJ for NJ/AL props. Only capture in G2 database. Work item set to Parth.

**Comment by mkoza178** [comment]
Turned off ChangeEmail events to post to CJ.
When doing a new start, you should NOT see the email being updated in CJ by MG2.
