### ISSUE TITLE
Advance - NJ - new start cutoff timings

### ISSUE THREAD

**Issue by mkoza178** [mkoza178/PJACS-Implemenation#37]
We have updated this logic for just SL & TT in Test to make sure it's working correctly. 
Here are the rules for the start date to be selected when doing New Start workflow:

SL/TT logic:
If today is Sunday and it is before 11am, choose a start date of Monday or next available delivery date. 
If today is Sunday and it is after 11am, choose a start date of Tuesday or next available delivery date. 
 
If today is Monday and it is before 3pm, choose a start date of Tuesday or next available delivery date. 
If today is Monday and it is after 3pm, choose a start date of Wednesday or next available delivery date. 
 
If today is Tuesday and it is before 3pm, choose a start date of Wednesday or next available delivery date. 
If today is Tuesday and it is after 3pm, choose a start date of Thursday or next available delivery date. 
 
If today is Wednesday and it is before 3pm, choose a start date of Thursday or next available delivery date. 
If today is Wednesday and it is after 3pm, choose a start date of Friday or next available delivery date. 
 
If today is Thursday and it is before 3pm, choose a start date of Friday, Sat or Sunday or next available delivery date. 
If today is Thursday and it is after 3pm, choose a start date of Monday or next available delivery date.

**Comment by beckywallace** [comment]
I entered a start today (Thursday) after 3 p.m. and the start date in the event is 6/1.  According to the logic it should have selected a start date of Monday (6/4):

![image](https://user-images.githubusercontent.com/25667903/40809428-16a40bf0-64f0-11e8-9f46-dd0b3a0e00dc.png)

**Comment by mkoza178** [comment]
Re-opened with the dev team.

**Comment by mkoza178** [comment]
A bug was found in the logic. Updated, let's try again!
