### ISSUE TITLE
No dates shown available to submit complaint - ALABAMA (TFS 39273)

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/PJACS-Implemenation#39]
Subscriber is an active Wed/Fri/Sun subscriber but no dates are available to select to submit a delivery complaint.  This has happened regardless of subscriber for Alabama.

![image](https://user-images.githubusercontent.com/25667903/41116853-1a5e1068-6a51-11e8-9f89-8c164ae6845a.png)

![image](https://user-images.githubusercontent.com/25667903/41116941-4e872bfe-6a51-11e8-94a1-e90517057016.png)

**Comment by mkoza178** [comment]
TFS created. Our QA team saw this as well!

**Comment by mkoza178** [comment]
Need to re-check this account on Monday.

**Comment by mkoza178** [comment]
Try now. 

But very important we review that service types table in AL.
