### ISSUE TITLE
Implementation task - Confirm eNotify rules for SL 

### ISSUE THREAD

**Issue by mkoza178** [mkoza178/PJACS-Implemenation#7]
Select for eNotify if: 
1.	Account is active with HHL 51 or HHL 52 
a.	What about accounts with status of Future or Vacation?
2.	Does account need a registration attached to it? 
a.	If not, do we send the eNotify email to the Circ System Email we receive from your data?
b.	If an account has a registration attached to it, do we send an email to that email over the circ system email or send to both?
3.	Any other rules for selection?

**Comment by jvanzomeren** [comment]
1. Accounts with Future = No ENotify
    Accounts with Vacation = ENotify
2.a do not need to register to get notify but must be registered to access
2.b If registered that email takes priority

**Comment by mkoza178** [comment]
Got it, confirming with Stewart no additional business rule clarifications are needed.

**Comment by mkoza178** [comment]
Per Stewart: 
"I think if an account is registered,  the emails associated with the registration should be used AND the account email should be used as well."

Thoughts?

**Comment by jvanzomeren** [comment]
I’m fine with that better to over communicate.

Jon VanZomeren
jvanzomeren@advancelocal.com
616.254.0639
